backend-elasticsearch/src/main/java/org/hibernate/search/v6poc/backend/elasticsearch/search/predicate/impl/AllPredicateBuilderImpl.java, backend-elasticsearch/src/main/java/org/hibernate/search/v6poc/backend/elasticsearch/search/predicate/impl/SearchPredicateFactoryImpl.java, engine/src/main/java/org/hibernate/search/v6poc/search/dsl/predicate/AllPredicateContext.java, engine/src/main/java/org/hibernate/search/v6poc/search/dsl/predicate/BooleanJunctionPredicateContext.java, engine/src/main/java/org/hibernate/search/v6poc/search/dsl/predicate/SearchPredicateContainerContext.java, engine/src/main/java/org/hibernate/search/v6poc/search/dsl/predicate/impl/AllPredicateContextImpl.java, engine/src/main/java/org/hibernate/search/v6poc/search/dsl/predicate/impl/BuildingRootSearchPredicateDslContextImpl.java, engine/src/main/java/org/hibernate/search/v6poc/search/dsl/predicate/impl/QuerySearchPredicateDslContextImpl.java, engine/src/main/java/org/hibernate/search/v6poc/search/dsl/predicate/impl/SearchPredicateContainerContextImpl.java, engine/src/main/java/org/hibernate/search/v6poc/search/dsl/predicate/spi/DelegatingSearchPredicateContainerContextImpl.java, engine/src/main/java/org/hibernate/search/v6poc/search/dsl/predicate/spi/SearchTargetPredicateRootContext.java, engine/src/main/java/org/hibernate/search/v6poc/search/dsl/query/SearchQueryContext.java, engine/src/main/java/org/hibernate/search/v6poc/search/dsl/query/SearchQueryResultContext.java, engine/src/main/java/org/hibernate/search/v6poc/search/dsl/query/impl/SearchQueryContextImpl.java, engine/src/main/java/org/hibernate/search/v6poc/search/dsl/query/impl/SearchQueryWrappingDefinitionResultContextImpl.java, engine/src/main/java/org/hibernate/search/v6poc/search/dsl/sort/impl/BuildingRootSearchSortDslContextImpl.java, engine/src/main/java/org/hibernate/search/v6poc/search/dsl/sort/impl/QuerySearchSortDslContextImpl.java, engine/src/main/java/org/hibernate/search/v6poc/search/dsl/sort/spi/SearchTargetSortRootContext.java, engine/src/main/java/org/hibernate/search/v6poc/search/predicate/spi/AllPredicateBuilder.java, engine/src/main/java/org/hibernate/search/v6poc/search/predicate/spi/SearchPredicateFactory.java, integration-test/src/test/java/org/hibernate/search/v6poc/integrationtest/JavaBeanElasticsearchAnnotationMappingIT.java, integration-test/src/test/java/org/hibernate/search/v6poc/integrationtest/JavaBeanElasticsearchExtensionIT.java, integration-test/src/test/java/org/hibernate/search/v6poc/integrationtest/JavaBeanElasticsearchObjectFieldIT.java, integration-test/src/test/java/org/hibernate/search/v6poc/integrationtest/JavaBeanElasticsearchProgrammaticMappingIT.java, integration-test/src/test/java/org/hibernate/search/v6poc/integrationtest/JavaBeanElasticsearchRoutingIT.java, integration-test/src/test/java/org/hibernate/search/v6poc/integrationtest/OrmElasticsearchAnnotationMappingIT.java, integration-test/src/test/java/org/hibernate/search/v6poc/integrationtest/OrmElasticsearchProgrammaticMappingIT.java
@gsmet I'll merge right away, but I'm creating this PR so you can have a look.
This could fuel our reflexion about the Query DSL; we now have tons of possible syntaxes, and may want to find the "ideal" one and remove the others.
=> Dsl improvements

.travis.yml, README.md, integration-test/pom.xml, pom.xml, reports/pom.xml
Reports should appear there, hopefully a few minutes after I submitted this PR: https://coveralls.io/github/hibernate/hibernate-search-6-poc
Example with my own fork: https://coveralls.io/github/yrodiere/hibernate-search-6-poc
=> Add test coverage reports using JaCoCo and Coveralls

integrationtest/backend-tck/src/main/java/org/hibernate/search/v6poc/integrationtest/backend/tck/util/rule/SearchSetupHelper.java
@yrodiere here is what we discussed this evening.
=> TCK - Prefix the index name with the class and test names

engine/pom.xml, engine/src/main/java/org/hibernate/search/v6poc/backend/index/impl/SimplifyingIndexManager.java, engine/src/main/java/org/hibernate/search/v6poc/logging/impl/ToStringTreeAppendableMultilineFormatter.java, engine/src/main/java/org/hibernate/search/v6poc/util/spi/ToStringStyle.java, engine/src/main/java/org/hibernate/search/v6poc/util/spi/ToStringTreeAppendable.java, engine/src/main/java/org/hibernate/search/v6poc/util/spi/ToStringTreeBuilder.java, engine/src/test/java/org/hibernate/search/v6poc/util/spi/ToStringTreeBuilderTest.java, integrationtest/util-common/src/main/java/org/hibernate/search/v6poc/integrationtest/util/common/assertion/StubIndexWorkAssert.java, integrationtest/util-common/src/main/java/org/hibernate/search/v6poc/integrationtest/util/common/assertion/StubTreeNodeAssert.java, integrationtest/util-common/src/main/java/org/hibernate/search/v6poc/integrationtest/util/common/rule/IndexWorkCall.java, integrationtest/util-common/src/main/java/org/hibernate/search/v6poc/integrationtest/util/common/rule/PushSchemaCall.java, integrationtest/util-common/src/main/java/org/hibernate/search/v6poc/integrationtest/util/common/stub/StubTreeNode.java, integrationtest/util-common/src/main/java/org/hibernate/search/v6poc/integrationtest/util/common/stub/StubTreeNodeCompare.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/logging/impl/Log.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/mapping/building/impl/PojoTypeManagerBuilder.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/mapping/impl/PojoTypeManager.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/model/spi/MemberPropertyHandle.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/processing/impl/NoOpPojoIndexingProcessor.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/processing/impl/PojoIndexingProcessor.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/processing/impl/PojoIndexingProcessorContainerElementNode.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/processing/impl/PojoIndexingProcessorPropertyNode.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/processing/impl/PojoIndexingProcessorTypeNode.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/processing/impl/PojoIndexingProcessorValueBridgeNode.java, orm/src/main/java/org/hibernate/search/v6poc/entity/orm/model/impl/GetterPropertyHandle.java
Example logs produced for `JavaBeanAnnotationMappingIT`:
```
10:17:08,593 (main) DEBUG PojoTypeManagerBuilder:78 - HSEARCH-POJO000017: Created POJO type manager: {
indexedJavaClass=class org.hibernate.search.v6poc.integrationtest.mapper.pojo.JavaBeanAnnotationMappingIT$YetAnotherIndexedEntity
identifierMapping=org.hibernate.search.v6poc.entity.pojo.mapping.impl.PropertyIdentifierMapping@d2cc05a
routingKeyProvider=org.hibernate.search.v6poc.entity.pojo.mapping.impl.RoutingKeyProvider$$Lambda$109/559670971@4f933fd1
processor={
class=PojoIndexingProcessorTypeNode
objectAccessors=[]
bridges=[
]
propertyNodes=[
{
class=PojoIndexingProcessorPropertyNode
handle=MemberPropertyHandle[public java.time.LocalDate org.hibernate.search.v6poc.integrationtest.mapper.pojo.JavaBeanAnnotationMappingIT$Parent …
```
=> Util for advanced toString building + log the detail of the PojoTypeManagers

backend-elasticsearch/src/main/java/org/hibernate/search/v6poc/backend/elasticsearch/logging/impl/Log.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/logging/impl/Log.java
As discussed on HipChat.
On top of https://github.com/hibernate/hibernate-search-6-poc/pull/34.
=> Reorganize loggers

mapper-javabean/src/main/java/org/hibernate/search/v6poc/entity/javabean/model/impl/JavaBeanTypeModel.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/mapping/building/impl/PojoIndexModelBinderImpl.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/mapping/building/impl/PojoTypeManagerBuilder.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/mapping/impl/PropertyIdentifierMapping.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/model/impl/AbstractPojoModelElement.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/model/impl/PojoModelNestedElement.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/model/impl/PojoModelPropertyRootElement.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/model/impl/PojoModelRootElementAccessor.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/model/impl/PojoModelTypeRootElement.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/model/spi/GenericContextAwarePojoGenericTypeModel.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/model/spi/PojoRawTypeModel.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/model/spi/PojoTypeModel.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/model/typepattern/impl/RawSuperTypeMatcher.java, mapper-pojo/src/test/java/org/hibernate/search/v6poc/entity/pojo/model/typepattern/impl/TypePatternMatcherFactoryTest.java, orm/src/main/java/org/hibernate/search/v6poc/entity/orm/model/impl/AbstractHibernateOrmTypeModel.java
This is useful for the upcoming PR introducing automatic reindexing, but makes sense even without that PR.
=> Cleanup of code related to casters and subtype testing

backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/search/dsl/sort/LuceneSearchSortContainerContext.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/search/dsl/sort/impl/LuceneSearchSortContainerContextImpl.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/search/sort/impl/LuceneSearchSortFactory.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/search/sort/impl/SearchSortFactoryImpl.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/search/sort/impl/UserProvidedLuceneSortSortContributor.java, integrationtest/backend-lucene/src/test/java/org/hibernate/search/v6poc/integrationtest/backend/lucene/ExtensionIT.java, integrationtest/backend-tck/src/main/java/org/hibernate/search/v6poc/integrationtest/backend/tck/util/rule/SearchSetupHelper.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/extractor/ContainerValueExtractorPath.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/util/impl/GenericTypeContext.java
* https://hibernate.atlassian.net/browse/HSEARCH-3095
=> HSEARCH-3095 Lucene native predicates/sorts

engine/src/main/java/org/hibernate/search/v6poc/cfg/spi/UnusedPropertyTrackingConfigurationPropertySource.java, integrationtest/orm/src/test/java/org/hibernate/search/v6poc/integrationtest/orm/OrmUnusedPropertiesIT.java, orm/src/main/java/org/hibernate/search/v6poc/entity/orm/bootstrap/impl/HibernateSearchIntegrator.java, orm/src/main/java/org/hibernate/search/v6poc/entity/orm/bootstrap/impl/HibernateSearchSessionFactoryObserver.java, orm/src/main/java/org/hibernate/search/v6poc/entity/orm/cfg/IndexingStrategyConfiguration.java, orm/src/main/java/org/hibernate/search/v6poc/entity/orm/cfg/SearchOrmSettings.java, orm/src/main/java/org/hibernate/search/v6poc/entity/orm/cfg/impl/HibernateOrmConfigurationPropertySource.java, orm/src/main/java/org/hibernate/search/v6poc/entity/orm/logging/impl/Log.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/v6poc/util/impl/integrationtest/common/rule/ExpectedLog4jLog.java
https://hibernate.atlassian.net//browse/HSEARCH-1869
=> HSEARCH-1869 Validate for each hibernate.search prefixed configuration property to be consumed

backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/types/codec/impl/LuceneFieldCodec.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/types/formatter/impl/LuceneFieldFormatter.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/types/formatter/impl/StringFieldFormatter.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/types/predicate/impl/LuceneFieldPredicateBuilderFactory.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/types/predicate/impl/StringFieldPredicateBuilderFactory.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/types/sort/impl/LuceneFieldSortContributor.java, integrationtest/backend-lucene/src/test/java/org/hibernate/search/v6poc/integrationtest/backend/lucene/search/LuceneSearchMultiIndexIT.java, integrationtest/backend-tck/src/main/java/org/hibernate/search/v6poc/integrationtest/backend/tck/search/SearchMultiIndexIT.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/v6poc/util/impl/integrationtest/common/assertion/AbstractSearchResultAssert.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/v6poc/util/impl/integrationtest/common/assertion/DocumentReferencesSearchResultAssert.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/v6poc/util/impl/integrationtest/common/assertion/SearchResultAssert.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/v6poc/util/impl/integrationtest/common/assertion/StubIndexWorkAssert.java
* https://hibernate.atlassian.net/browse/HSEARCH-3059
=> HSEARCH-3059 Test multi-index searches

engine/pom.xml, integrationtest/mapper-pojo/src/test/java/org/hibernate/search/v6poc/integrationtest/mapper/pojo/JavaBeanAnnotationMappingDiscoveryIT.java, integrationtest/mapper-pojo/src/test/java/org/hibernate/search/v6poc/integrationtest/mapper/pojo/JavaBeanAnnotationMappingIT.java, integrationtest/mapper-pojo/src/test/java/org/hibernate/search/v6poc/integrationtest/mapper/pojo/JavaBeanGenericPropertyIT.java, integrationtest/mapper-pojo/src/test/java/org/hibernate/search/v6poc/integrationtest/mapper/pojo/JavaBeanProgrammaticMappingIT.java, integrationtest/mapper-pojo/src/test/java/org/hibernate/search/v6poc/integrationtest/mapper/pojo/JavaBeanPropertyInheritanceIT.java, integrationtest/mapper-pojo/src/test/java/org/hibernate/search/v6poc/integrationtest/mapper/pojo/bridge/CustomPropertyBridge.java, integrationtest/mapper-pojo/src/test/java/org/hibernate/search/v6poc/integrationtest/mapper/pojo/bridge/CustomTypeBridge.java, integrationtest/mapper-pojo/src/test/java/org/hibernate/search/v6poc/integrationtest/mapper/pojo/bridge/IntegerAsStringValueBridge.java, integrationtest/mapper-pojo/src/test/java/org/hibernate/search/v6poc/integrationtest/mapper/pojo/bridge/OptionalIntAsStringValueBridge.java, integrationtest/orm/src/test/java/org/hibernate/search/v6poc/integrationtest/orm/OrmAnnotationMappingDiscoveryIT.java, integrationtest/orm/src/test/java/org/hibernate/search/v6poc/integrationtest/orm/OrmAnnotationMappingIT.java, integrationtest/orm/src/test/java/org/hibernate/search/v6poc/integrationtest/orm/OrmGenericPropertyIT.java, integrationtest/orm/src/test/java/org/hibernate/search/v6poc/integrationtest/orm/OrmProgrammaticMappingIT.java, integrationtest/orm/src/test/java/org/hibernate/search/v6poc/integrationtest/orm/OrmPropertyInheritanceIT.java, integrationtest/orm/src/test/java/org/hibernate/search/v6poc/integrationtest/orm/OrmUnusedPropertiesIT.java, integrationtest/orm/src/test/java/org/hibernate/search/v6poc/integrationtest/orm/bridge/CustomPropertyBridge.java, integrationtest/orm/src/test/java/org/hibernate/search/v6poc/integrationtest/orm/bridge/CustomTypeBridge.java, integrationtest/orm/src/test/java/org/hibernate/search/v6poc/integrationtest/orm/bridge/IntegerAsStringValueBridge.java, integrationtest/orm/src/test/java/org/hibernate/search/v6poc/integrationtest/orm/bridge/OptionalIntAsStringValueBridge.java, mapper-pojo/pom.xml, pom.xml, util/internal/integrationtest/common/pom.xml, util/internal/integrationtest/common/src/main/java/org/hibernate/search/v6poc/util/impl/integrationtest/common/stub/backend/index/impl/StubIndexManager.java, util/internal/test/pom.xml, util/internal/test/src/main/java/org/hibernate/search/v6poc/util/impl/test/rule/ExpectedLog4jLog.java, util/internal/test/src/main/java/org/hibernate/search/v6poc/util/impl/test/rule/StaticCounters.java
https://hibernate.atlassian.net//browse/HSEARCH-3165
=> HSEARCH-3165 Search 6 groundwork - Add a a test utils module for classes useful for any test (even unit tests)

backend-elasticsearch/src/main/java/org/hibernate/search/v6poc/backend/elasticsearch/document/model/dsl/impl/AbstractElasticsearchIndexSchemaObjectNodeBuilder.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/document/model/dsl/impl/AbstractLuceneIndexSchemaObjectNodeBuilder.java, engine/src/main/java/org/hibernate/search/v6poc/engine/impl/SearchMappingRepositoryBuilderImpl.java, integrationtest/backend-tck/src/main/java/org/hibernate/search/v6poc/integrationtest/backend/tck/util/rule/SearchSetupHelper.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/dirtiness/building/impl/AbstractPojoImplicitReindexingResolverTypeNodeBuilder.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/dirtiness/building/impl/PojoImplicitReindexingResolverBuildingHelper.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/dirtiness/building/impl/PojoImplicitReindexingResolverPropertyNodeBuilder.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/dirtiness/building/impl/PojoImplicitReindexingResolverValueNodeBuilderDelegate.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/dirtiness/building/impl/PojoIndexingDependencyCollectorValueNode.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/mapping/building/impl/PojoMapper.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/mapping/definition/annotation/impl/AnnotationMappingDefinitionImpl.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/mapping/definition/programmatic/impl/ProgrammaticMappingDefinitionImpl.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/mapping/impl/ChangesetPojoContainedTypeWorker.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/mapping/impl/ChangesetPojoIndexedTypeWorker.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/mapping/impl/ChangesetPojoWorkerImpl.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/mapping/impl/PojoContainedTypeManagerContainer.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/mapping/impl/PojoIndexedTypeManagerContainer.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/model/additionalmetadata/building/impl/PojoPropertyAdditionalMetadataBuilder.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/model/additionalmetadata/building/impl/PojoTypeAdditionalMetadataBuilder.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/model/impl/AbstractPojoModelElement.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/processing/building/impl/PojoIndexingProcessorPropertyNodeBuilder.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/processing/building/impl/PojoIndexingProcessorTypeNodeBuilder.java, orm/src/main/java/org/hibernate/search/v6poc/entity/orm/mapping/impl/HibernateOrmMetatadaContributor.java
https://hibernate.atlassian.net//browse/HSEARCH-3166
=> HSEARCH-3166 Search 6 groundwork - Use LinkedHashMap/LinkedHashSet for maps/sets that are iterated on for easier debugging

orm/src/main/java/org/hibernate/search/v6poc/entity/orm/mapping/impl/HibernateOrmMappingInitiator.java, orm/src/main/java/org/hibernate/search/v6poc/entity/orm/mapping/impl/HibernateOrmMetatadaContributor.java, orm/src/main/java/org/hibernate/search/v6poc/entity/orm/model/impl/HibernateOrmBootstrapIntrospector.java, util/internal/common/src/main/java/org/hibernate/search/v6poc/util/impl/common/StreamHelper.java, util/internal/integrationtest/common/src/main/java/org/hibernate/search/v6poc/util/impl/integrationtest/common/stub/StubTreeNode.java
https://hibernate.atlassian.net//browse/HSEARCH-3182
=> HSEARCH-3182 Sort Hibernate ORM metadata before processing it

integrationtest/mapper-pojo/src/test/java/org/hibernate/search/v6poc/integrationtest/mapper/pojo/JavaBeanAnnotationMappingRoutingIT.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/bridge/declaration/RoutingKeyBridgeAnnotationBuilderReference.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/bridge/declaration/RoutingKeyBridgeMapping.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/bridge/declaration/RoutingKeyBridgeReference.java, mapper-pojo/src/main/java/org/hibernate/search/v6poc/entity/pojo/mapping/definition/annotation/impl/AnnotationPojoTypeMetadataContributorImpl.java
https://hibernate.atlassian.net//browse/HSEARCH-3078
~This PR is based on #70, which should be merged first.~ => Done
=> HSEARCH-3078 Search 6 groundwork - Add a mapping annotation for routing key bridges

backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/document/impl/LuceneIndexFieldAccessor.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/document/model/LuceneFieldContributor.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/document/model/LuceneFieldValueExtractor.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/document/model/dsl/LuceneIndexSchemaFieldContext.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/document/model/dsl/impl/LuceneIndexSchemaFieldContextImpl.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/document/model/impl/LuceneIndexModel.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/document/model/impl/LuceneIndexSchemaFieldNode.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/logging/impl/Log.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/search/query/impl/HitExtractor.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/search/query/impl/SearchQueryFactoryImpl.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/types/codec/impl/LuceneFieldCodec.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/types/codec/impl/LuceneFieldFieldCodec.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/types/dsl/impl/IntegerIndexSchemaFieldContext.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/types/dsl/impl/LuceneFieldIndexSchemaFieldContext.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/types/formatter/impl/SimpleCastingFieldFormatter.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/types/predicate/impl/IntegerFieldPredicateBuilderFactory.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/types/predicate/impl/IntegerMatchPredicateBuilder.java, backend-lucene/src/main/java/org/hibernate/search/v6poc/backend/lucene/types/predicate/impl/IntegerRangePredicateBuilder.java, integrationtest/backend-lucene/src/test/java/org/hibernate/search/v6poc/integrationtest/backend/lucene/ExtensionIT.java
* https://hibernate.atlassian.net/browse/HSEARCH-3127
=> HSEARCH-3127 Allow declaring native Lucene fields in the schema

pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3241
Should only be merged after https://github.com/hibernate/hibernate-search/pull/1711
=> HSEARCH-3241 Reorganize and clarify Maven properties used to pass JVM args

.travis.yml
https://hibernate.atlassian.net//browse/HSEARCH-3240
=> HSEARCH-3240 Use the pre-installed JDK in the Travis build instead of trying to update it in each build

integrationtest/showcase/library/src/main/java/org/hibernate/search/v6poc/integrationtest/showcase/library/bridge/AccountBorrowalSummaryBridge.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/v6poc/integrationtest/showcase/library/bridge/annotation/AccountBorrowalSummaryBridge.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/v6poc/integrationtest/showcase/library/dao/DaoFactory.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/v6poc/integrationtest/showcase/library/dao/PersonDao.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/v6poc/integrationtest/showcase/library/dao/syntax/fluidandlambda/FluidAndLambdaSyntaxDaoFactory.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/v6poc/integrationtest/showcase/library/dao/syntax/fluidandlambda/FluidAndLambdaSyntaxPersonDao.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/v6poc/integrationtest/showcase/library/dao/syntax/fluidandobject/FluidAndObjectSyntaxDaoFactory.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/v6poc/integrationtest/showcase/library/dao/syntax/fluidandobject/FluidAndObjectSyntaxPersonDao.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/v6poc/integrationtest/showcase/library/dao/syntax/lambda/LambdaSyntaxDaoFactory.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/v6poc/integrationtest/showcase/library/dao/syntax/lambda/LambdaSyntaxPersonDao.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/v6poc/integrationtest/showcase/library/dao/syntax/object/ObjectSyntaxDaoFactory.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/v6poc/integrationtest/showcase/library/dao/syntax/object/ObjectSyntaxPersonDao.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/v6poc/integrationtest/showcase/library/model/AbstractEntity.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/v6poc/integrationtest/showcase/library/model/Account.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/v6poc/integrationtest/showcase/library/model/Borrowal.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/v6poc/integrationtest/showcase/library/model/BorrowalType.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/v6poc/integrationtest/showcase/library/model/Document.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/v6poc/integrationtest/showcase/library/model/DocumentCopy.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/v6poc/integrationtest/showcase/library/model/Library.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/v6poc/integrationtest/showcase/library/model/Person.java, integrationtest/showcase/library/src/main/java/org/hibernate/search/v6poc/integrationtest/showcase/library/model/ProgrammaticMappingContributor.java, integrationtest/showcase/library/src/test/java/org/hibernate/search/v6poc/integrationtest/showcase/OrmElasticsearchLibraryShowcaseIT.java
https://hibernate.atlassian.net//browse/HSEARCH-3250
=> HSEARCH-3250 Search 6 groundwork - Add a complex bridge example to the Library showcase

README.md
A+ code quality score is definitely something to be proud of :slightly_smiling_face:
=> Add LGTM.com Java code quality badge

.travis.yml, pom.xml
https://hibernate.atlassian.net//browse/HSEARCH-3252
Port of https://github.com/hibernate/hibernate-search/pull/1719, which should be merged first.
=> HSEARCH-3252 Avoid using _JAVA_OPTIONS in Travis builds

Jenkinsfile, integrationtest/orm/pom.xml, integrationtest/orm/src/test/java/org/hibernate/search/v6poc/integrationtest/orm/OrmAnnotationMappingIT.java, integrationtest/orm/src/test/java/org/hibernate/search/v6poc/integrationtest/orm/OrmAutomaticIndexingEmbeddableIT.java, integrationtest/orm/src/test/java/org/hibernate/search/v6poc/integrationtest/orm/OrmAutomaticIndexingMapKeysAssociationIT.java, integrationtest/orm/src/test/java/org/hibernate/search/v6poc/integrationtest/orm/OrmAutomaticIndexingMapValuesAssociationIT.java, integrationtest/orm/src/test/java/org/hibernate/search/v6poc/integrationtest/orm/OrmProgrammaticMappingIT.java, integrationtest/showcase/library/pom.xml, pom.xml, util/internal/integrationtest/orm/pom.xml, util/internal/integrationtest/orm/src/main/resources/hibernate.properties
https://hibernate.atlassian.net//browse/HSEARCH-3239
Follows up on #86 to fix the build for PostgreSQL and MySQL. I should have tested the full build after I rebased...
This also adds a bit of security-related documentation, and previously missing support for re-building when a comment is added to the pull request.
=> Follow-up: HSEARCH-3239 Setup a Jenkins pipeline build with a Jenkinsfile

Jenkinsfile
https://hibernate.atlassian.net//browse/HSEARCH-3294
~This is based on #95 , which should be merged first.~ => Done
=> HSEARCH-3294 Send email notifications upon build failures in the Jenkinsfile
